"""Added estimated delivery column

Revision ID: 7eb6065248a3
Revises: 
Create Date: 2026-03-22 21:12:29.699313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb6065248a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery', sa.String(length=100), nullable=True))

    with op.batch_alter_table('saree', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.TEXT(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery')

    # ### end Alembic commands ###
